import 'package:flutter/material.dart';
import 'package:risk_assessment_flutter/constants.dart';
import 'package:risk_assessment_flutter/next_button.dart';
import 'sign_in.dart';
import 'package:risk_assessment_flutter/appbar.dart';

class Agreement extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: myAppBar(),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          Container(
            padding: EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'ABOUT THE APP',
                  style: kHeaderTextStyle,
                ),
                Text(
                  'SAHARA (the Safety and Hazard Assessment Risk App) was created with support from the Government of Alberta Creative Sentencing Program and is powered by SWIFT Learning. SAHARA was developed in conjunction with the custom eLearning course “Risk Tolerance and Personal Safety,” which is available for free through the SWIFT HSE Course Library. This app is intended to be a learning tool to explore the relationship between hazards around you and your mindset to determine your total risk level in a given scenario.',
                  style: kBodyTextStyle,
                ),
              ],
            ),
          ),
          Container(
            padding: EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'DISCLAIMER',
                  style: kHeaderTextStyle,
                ),
                Text(
                  'This app is intended to be a learning tool for education purposes only, and to be used with the associated eLearning courseware. The results generated by using this app are not necessarily accurate. By clicking “Accept,” you understand these terms and agree that The Safety in Schools Foundation of Canada, SWIFT Learning and any of their partners or associates bear no responsibility for any damages or injuries that occur from using this app.',
                  style: kBodyTextStyle,
                ),
              ],
            ),
          ),
          NextButton(
            buttonText: 'Click to Accept',
            nextWidget: SignIn(),
          ),
        ],
      ),
    );
  }
}
